### ISSUE TITLE
Autorefresh after enabling/disabling

### ISSUE THREAD

**Issue by SW1FT** [animeshkundu/youtube-audio#2]
Self-explanatory, this would save a click and be more convenient.

**Comment by animeshkundu** [comment]
Yes, that would be definitely more convenient.

**Comment by animeshkundu** [comment]
ba852a90e0fba1dbaeaa5778b1f15f9e2ef88763 would refresh the page on extension toggle only if the current active tab is youtube

**Comment by animeshkundu** [comment]
This should have been fixed. Could you check and resolve the issue ?

**Comment by SW1FT** [comment]
This is fixed, thanks!
