### ISSUE TITLE
Access your data for all webpages?

### ISSUE THREAD

**Issue by drasbeck** [animeshkundu/youtube-audio#7]
Is this permission really necessary for the extension to run? Can't it be isolated to youtube.com? It seems quite excessive in regards to privacy.

**Comment by hbons** [comment]
Wondering this as well. This stopped me from this very useful extension. It's great that it's open source and I can check the code, but I don't know if it's the same as on Firefox Addons.

Thanks for this extension. :) Would be great if this could be sorted.

**Comment by animeshkundu** [comment]
Thanks for pointing this out, would address this in the next release
