### ISSUE TITLE
[Feature Request] Add option to remove the video message

### ISSUE THREAD

**Issue by maverick74** [animeshkundu/youtube-audio#9]
Add option to remove the video message from the video background (Leaving it black, for example).

Reason: using Popup Video addon with Youtube Audio addon i can create a small popup window that will have just the video control buttons. However setting it's size to say 50px height, the message gets behind the player controls making them hard to see.

**Comment by animeshkundu** [comment]
Thank you @NathanJRollins :)

**Comment by maverick74** [comment]
Thanks :)
